definitions:
  services:
    docker:
      memory: 2048
  steps:
    - step: &build
        name: Build Project
        size: 2x
        image: node:alpine
        caches:
          - node
        script:
          - export NODE_OPTIONS=--openssl-legacy-provider
          - npm install --legacy-peer-deps
          - npm run build
        artifacts:
          - 'dist/SampleAngular/**'
    - step: &push-image
        name: Push Image
        services:
          - docker
        image: atlassian/default-image:3
        script:
          - docker login $DOCKER_REPOSITORY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker build -t $DOCKER_REPOSITORY/frontend/$PROJECT:latest .
          - docker push $DOCKER_REPOSITORY/frontend/$PROJECT:latest
    - step: &deploy
        name: Deploy to Server
        services:
          - docker
        image: atlassian/default-image:3
        script:
          - docker login $DOCKER_REPOSITORY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker-compose -H ssh://$REMOTE_SERVER pull
          - docker-compose -H ssh://$REMOTE_SERVER -p "$PROJECT" up -d
pipelines:
  branches:
    master:
      - step: *build
      - step: *push-image
      - step:
          <<: *deploy
          deployment: test
